function opts = sample_mission_params(shape, u)
% SAMPLE_MISSION_PARAMS  Map one row of an LHS design (values in (0,1)) to
% an opts struct for generate_mission_profile.m, using shape-specific
% physical ranges. u must have at least as many columns as the shape's
% dimension list below; extra columns are ignored (lets one shared LHS
% design array be sliced per shape without re-generating it).
%
% Typical use: build one LHS design per shape with simple_lhs.m, then call
% this once per row to get that mission's actual continuous parameters.

switch shape
    case 'long_loiter'
        dims = { ...
            'cruise_altitude_m',    [2000, 4500]; ...
            'loiter_duration_s',    [1800, 6000]; ...
            'loiter_throttle',      [0.45, 0.60]; ...
            'throttle_jitter_sigma',[0.01, 0.05]; ...
            'weather_isa_offset_c', [-15,  20] };

    case 'short_patrol'
        dims = { ...
            'patrol_altitude_m',    [800,  2200]; ...
            'patrol_duration_s',    [600,  1200]; ...
            'patrol_throttle',      [0.45, 0.65]; ...
            'throttle_jitter_sigma',[0.01, 0.05]; ...
            'weather_isa_offset_c', [-15,  20] };

    case 'high_altitude_transit'
        dims = { ...
            'transit_altitude_m',   [5490, 7200]; ... % published ceiling to +31% -- see
                                                        % docs/build_plan.md's Step 6 log: above
                                                        % ~7500-8000m EGT/AFR run into territory the
                                                        % model was never validated for (no ECU-style
                                                        % altitude derate limiter exists), confirmed via
                                                        % verify_batch.m catching two real EGT>1200C FAILs
            'transit_duration_s',   [1200, 2400]; ...
            'transit_throttle',     [0.55, 0.70]; ...
            'throttle_jitter_sigma',[0.01, 0.04]; ...
            'weather_isa_offset_c', [-20,  10] };

    case 'hot_day_ground_ops'
        dims = { ...
            'hot_isa_offset_c',     [25,   38]; ...
            'runup_throttle',       [0.60, 0.85]; ...
            'runup_duration_s',     [180,  420] };

    case 'high_throttle_climb_heavy'
        dims = { ...
            'climb_altitude_m',     [3000, 5500]; ...
            'slam_hold_throttle',   [0.90, 1.00]; ...
            'slam_hold_duration_s', [400,  900]; ...
            'throttle_jitter_sigma',[0.01, 0.03] };

    otherwise
        error('sample_mission_params:unimplementedShape', ...
            'No parameter-sampling ranges defined for shape "%s".', shape);
end

if size(u,2) < size(dims,1)
    error('sample_mission_params:tooFewColumns', ...
        'shape "%s" needs %d LHS dimensions, got %d.', shape, size(dims,1), size(u,2));
end

opts = struct();
for i = 1:size(dims,1)
    name = dims{i,1};
    lo = dims{i,2}(1); hi = dims{i,2}(2);
    opts.(name) = lo + u(i)*(hi-lo);
end
end
