"""add health_parameters json to health_scores

Revision ID: 16431cbf99b4
Revises: 2b08beb8d326
Create Date: 2026-09-04 05:03:15.235574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16431cbf99b4"
down_revision: Union[str, Sequence[str], None] = "2b08beb8d326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("health_scores", sa.Column("health_parameters", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_scores", "health_parameters")
    # ### end Alembic commands ###
