"""add autoencoder anomaly fields to health_scores

Revision ID: 2b08beb8d326
Revises: ea13eb8b9d97
Create Date: 2026-09-03 03:15:47.618301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b08beb8d326'
down_revision: Union[str, Sequence[str], None] = 'ea13eb8b9d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_scores', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.add_column('health_scores', sa.Column('is_anomalous', sa.Boolean(), nullable=True))
    op.add_column('health_scores', sa.Column('anomaly_model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_scores', 'anomaly_model_version')
    op.drop_column('health_scores', 'is_anomalous')
    op.drop_column('health_scores', 'anomaly_score')
    # ### end Alembic commands ###
