"""add forecast_horizon_s to health_scores

Revision ID: 90bdc44f934d
Revises: 985417695fbd
Create Date: 2026-09-03 01:29:35.621584

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90bdc44f934d"
down_revision: Union[str, Sequence[str], None] = "985417695fbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (a NOT NULL add with no default
    # fails against any table that already has data, e.g. a populated
    # Supabase deployment) -- 0.0 matches the ground-truth stand-in's own
    # "describes the current instant, not a forecast" meaning.
    op.add_column(
        "health_scores",
        sa.Column("forecast_horizon_s", sa.Float(), nullable=False, server_default="0.0"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_scores", "forecast_horizon_s")
    # ### end Alembic commands ###
