"""init schema

Revision ID: 985417695fbd
Revises: 
Create Date: 2026-09-02 01:45:53.160742

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '985417695fbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('mission_shape', sa.String(), nullable=True),
    sa.Column('fault_class', sa.String(), nullable=True),
    sa.Column('accumulated_hours_at_start', sa.Float(), nullable=True),
    sa.Column('n_rows', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('export_rate_hz', sa.Float(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('advisory_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advisory_text', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('fault_type', sa.String(), nullable=False),
    sa.Column('fault_probability', sa.Float(), nullable=False),
    sa.Column('health_index', sa.Float(), nullable=False),
    sa.Column('rul_estimate_hours', sa.Float(), nullable=True),
    sa.Column('rul_lower', sa.Float(), nullable=True),
    sa.Column('rul_upper', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_scores_run_ts', 'health_scores', ['run_id', 'ts'], unique=False)
    op.create_table('residuals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_residuals_run_ts', 'residuals', ['run_id', 'ts'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('data_origin', sa.String(), nullable=False),
    sa.Column('rpm', sa.Float(), nullable=False),
    sa.Column('torque', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('engine_load', sa.Float(), nullable=False),
    sa.Column('cht_c1', sa.Float(), nullable=False),
    sa.Column('cht_c2', sa.Float(), nullable=False),
    sa.Column('cht_c3', sa.Float(), nullable=False),
    sa.Column('cht_c4', sa.Float(), nullable=False),
    sa.Column('egt_c1', sa.Float(), nullable=False),
    sa.Column('egt_c2', sa.Float(), nullable=False),
    sa.Column('egt_c3', sa.Float(), nullable=False),
    sa.Column('egt_c4', sa.Float(), nullable=False),
    sa.Column('oil_pressure', sa.Float(), nullable=False),
    sa.Column('oil_temperature', sa.Float(), nullable=False),
    sa.Column('fuel_flow', sa.Float(), nullable=False),
    sa.Column('rail_pressure', sa.Float(), nullable=False),
    sa.Column('injection_timing', sa.Float(), nullable=False),
    sa.Column('boost_pressure', sa.Float(), nullable=False),
    sa.Column('map', sa.Float(), nullable=False),
    sa.Column('intake_temperature', sa.Float(), nullable=False),
    sa.Column('air_mass_flow', sa.Float(), nullable=False),
    sa.Column('coolant_temperature', sa.Float(), nullable=False),
    sa.Column('vibration_rms_x', sa.Float(), nullable=True),
    sa.Column('vibration_order_1x', sa.Float(), nullable=True),
    sa.Column('vibration_rms_x_bearing_proxy', sa.Float(), nullable=False),
    sa.Column('vibration_order_1x_bearing_proxy', sa.Float(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=False),
    sa.Column('battery_current', sa.Float(), nullable=False),
    sa.Column('alternator_power', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('ambient_pressure', sa.Float(), nullable=False),
    sa.Column('ambient_temperature', sa.Float(), nullable=False),
    sa.Column('air_density', sa.Float(), nullable=False),
    sa.Column('throttle', sa.Float(), nullable=False),
    sa.Column('engine_state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_run_ts', 'telemetry', ['run_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_run_ts', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('ix_residuals_run_ts', table_name='residuals')
    op.drop_table('residuals')
    op.drop_index('ix_health_scores_run_ts', table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_table('advisory_state')
    op.drop_table('runs')
    # ### end Alembic commands ###
